include:
  - project: 'system/gitlab/common'
    ref: v4.6.0
    file: '/templates/gitlab-ci/python/common.yml'

  - project: 'system/gitlab/common'
    ref: v4.6.0
    file: '/templates/gitlab-ci/python/package.yml'


variables:
  POETRY_INSTALL_CMD: "poetry install -vvv --no-interaction --all-extras"
  CUSTOM_POETRY_VERSION: 1.8.2


.python:
  tags:
    - python-structure-based-nordkit
