include:
  - project: 'system/gitlab/common'
    ref: v4.3.3
    file: '/templates/gitlab-ci/python/common.yml'

  - project: 'system/gitlab/common'
    ref: v4.3.3
    file: '/templates/gitlab-ci/python/package.yml'

.python:
  tags:
    - python-structure-based-nordkit
