repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run task pc-black
        pass_filenames: true
        types: [file, json, python]
        language: system

  - repo: local
    hooks:
      - id: linter
        name: Flake8
        entry: poetry run task pc-linter
        pass_filenames: true
        types: [file, python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run task pc-isort
        pass_filenames: true
        types: [file, python]
        language: system

  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run task pc-mypy
        pass_filenames: true
        types: [file, python]
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: debug-statements
